### PR TITLE
API to pre-setup token & chainIds, along with bridge drop down

### PR DESCRIPTION
**Pull request by dan13ram**
We now support the bridge drop-down between three different bridge directions: [eth-xdai, bsc-xdai, kovan-sokol]
We will only support eth-xdai and bsc-xdai in production.

We also support an API form, for users to embed into their UIs or docs. 

Example: https://sokol-omnibridge.web.app/bridge?from=77&to=42&token=0x263a0b2141a2982b17b3a28f50f2eef303563000

@maxaleks Can you please update the bsc-xdai and xdai-bsc subgraphs, with the latest subgraph code from `master` branch. Now we support alternative receivers in the history tab.

I request this because the UI throws up when user changes to history tab when `BSC-XDAI` bridge is chosen, and the frontend is expecting a different schema on the subgraph.

### CODE REVIEW

**Comment by maxaleks** [comment]
Hi @dan13ram!
Sorry for the delay, I had a little vacation. Subgraphs are updated now!

**Comment by dan13ram** [comment]
> Hi @dan13ram!
> Sorry for the delay, I had a little vacation. Subgraphs are updated now!

Thank you @maxaleks , Hope you had a wonderful vacation =)

**Comment by akolotov** [comment]
Hi @dan13ram 

I have tried the link you provided when MM was connected to the Kovan chain and the following error appear:

image

Imagine a real case: A user's MM is connected to the Mainnet. The user is interacting with an app on the xDai side where it is suggested to bridge tokens from the xDai chain to the Ethereum Mainnet by pressing the corresponding link which leads to the OB UI. After clicking on the link the user will be forwarded to the OB UI but it will report that the token is not found. It will definitely confuse. Don't you think that more suitable way is to request the user to change the network is such situation?

Thanks,

**Comment by sunguru98** [comment]
That's weird @akolotov, 
Screenshot 2021-04-02 at 2 48 56 AM
It's asking to switch networks atleast for me .. 
Could it be a reverse bridge issue or something @dan13ram?

**Comment by sunguru98** [comment]
I guess the condition bypasses due to checking whether the chainId includes either foreign or home .. 
Fixing this should show up correct ..

**Comment by dan13ram** [comment]
Thanks @akolotov Thats definitely a bug. Will fix it soon

**Pull request merged**
