### PR TITLE
fixed DATA bridge address

### PR DESCRIPTION
**Pull request by dan13ram**

### CODE REVIEW

**Comment by hpihkala** [comment]
Aaaaah, those were supposed to be the mediator addresses, looks like you accidentally put the token addresses there @jtakalai! We couldn't easily test the subgraph part of the changes in #171, enabling this mistake to happen.

This must be the root cause of the subgraph problems for sure?

Just to triple-check, here is the correct set of addresses:

- DATA token on mainnet: `0x0Cf0Ee63788A0849fE5297F3407f701E122cC023`
- DATA mediator on mainnet: `0x2eeeDdeECe91c9F4c5bA4C8E1d784A0234C6d015`
- DATA token on xDai: `0xE4a2620edE1058D61BEe5F45F6414314fdf10548`
- DATA mediator on xDai: `0x7d55f9981d4E10A193314E001b96f72FCc901e40`

**Review by hpihkala — APPROVED** [review]
This LGTM under the assumption that those should be the mediator addresses. Which they now are! I also verified `startBlock` is the correct block when the contract was deployed.

**Comment by jtakalai** [comment]
hmm, interesting, because I did hand-test sending the token both ways on my local installation and it worked fine. Good catch!

**Review by jtakalai — APPROVED** [review]

**Comment by jtakalai** [comment]
double checked addresses, they are contracts deployed at those block numbers in the respective chains

**Comment by dan13ram** [comment]
@jtakalai for sending and receiving tokens, we get the required information by indexing the AMB's events.

The dedicated bridges' events as well as the omnibridge mediator's events are indexed and used only for fetching history as well as tokenInfo for the frontend. This is why you could send and receive the tokens without any issues =)

**Comment by dan13ram** [comment]
@jtakalai and @hpihkala I double-checked and the UI is now showing the DATA tokens on both side.

But noticed that honey-swap token-list has a different token-address for Streamr DATA:
```
{
"name": "Streamr DATAcoin on xDai",
"address": "0x796879025A627d34042E3eDd2E239E75ba4445e6",
"symbol": "DATA",
"decimals": 18,
"chainId": 100,
"logoURI": "https://etherscan.io/token/images/streamr2_28.png"
}
```

We fetch both this token-list as well as from our subgraph and combine the two to show on the UI. Thus, currently both the above token as well as `0xE4a2620edE1058D61BEe5F45F6414314fdf10548` are showing up.

To correct this, you shall have to follow with 1hive team and get it fixed @ https://github.com/1Hive/default-token-list/blob/master/src/tokens/xdai.json

**Comment by dan13ram** [comment]
Merging this PR, and closing the issue. Please reopen your issue in case you have any further issues :)

**Pull request merged**
