### PR TITLE
Override for DATA token

### PR DESCRIPTION
**Pull request by jtakalai**
Overrides for DATA token, similar to how https://github.com/xdaichain/omnibridge/pull/128 was done for HNY

### CODE REVIEW

**Comment by jtakalai** [comment]
Submitted a draft, for your review and feedback

**Comment by jtakalai** [comment]
ok hand-tested locally, working, DATA moves fine both ways.

**Review by dan13ram — APPROVED** [review]
LGTM, will deploy the subgraphs and then deploy the frontend :)

**Comment by jtakalai** [comment]
awesome fast response, thanks!

**Comment by hpihkala** [comment]
@dan13ram Thanks for merging and deploying the code! A couple of things I noticed while testing:

- The token unfortunately doesn't come up via the token select/search function in the UI. Sounds like something didn't work out with the subgraphs? It works via the "Add custom token" feature, not out of the box.

Screen Shot 2021-03-15 at 11 43 13

- Another thing I noticed was that for `approve`, the gas limit provided/estimated by default was 45,160, and the transaction ran out of gas and failed. I tried again by manually setting the gas limit higher, and it actually required 45,184 to pass. I was using Metamask, if that makes any difference.

We're hoping to launch the related features tomorrow Tuesday or on Wednesday, so would be good to get those final bits ironed out! Would you like us to submit separate issues out of these?

**Comment by dan13ram** [comment]
@jtakalai and @hpihkala 
There is indeed a bug in the subgraph. I'm looking into it presently. Will keep you guys updated on the issue you have raised :)

**Pull request merged**
